window.TREASURE_CONFIG = {
  apiUrl: "https://script.google.com/macros/s/AKfycbyRsMS69qw-F7-yCl8G-wjjkKo0b5pycJE4jy_z7VQsKcEu0V1k8T6NTUkyAlh0ymv5PQ/exec",
  appName: "Treasure Island | เกาะมหาสมบัติ",
  lpsMaxScore: 2,
  totalAcMaxScore: 3,
  demoUsername: "demo",
  demoScenes: {
    start: {
      scene_id: "start",
      scene_title: "แผนที่ในขวดแก้ว",
      scene_type: "NAR",
      parent_scene: "",
      video_url: "",
      background_image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
      audio_url: "",
      scene_text: "พายุพัดพาคุณมาติดอยู่บนชายฝั่งใต้แสงจันทร์ ภายในขวดแก้วมีแผนที่ฉีกขาด ชี้ไปยังป่าทึบและแนวปะการังที่มีสัญลักษณ์กะโหลก",
      choice_1_text: "เดินตามเส้นทางเข้าไปในป่า",
      choice_1_next_scene: "ctq_compass",
      choice_1_AS: 0,
      choice_1_MS: 0,
      choice_2_text: "สำรวจแนวปะการังก่อน",
      choice_2_next_scene: "ctq_compass",
      choice_2_AS: 0,
      choice_2_MS: 0,
      success_redirect: "",
      fail_redirect: "",
      retry_allowed: true,
      allow_save: true,
      ending_type: "",
      score_type: "",
      max_score: 2
    },
    ctq_compass: {
      scene_id: "ctq_compass",
      scene_title: "เข็มทิศที่เสียหาย",
      scene_type: "CTQ",
      parent_scene: "start",
      video_url: "",
      background_image: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1600&q=80",
      audio_url: "",
      scene_text: "เข็มทิศหมุนอย่างผิดปกติใกล้หินสลัก คุณควรใช้หลักฐานใดนำทางการตัดสินใจครั้งต่อไป",
      choice_1_text: "เชื่อแผนที่เก่า เพราะแผนที่ระบุชื่ออ่าวไว้",
      choice_1_next_scene: "ct2_reason",
      choice_1_AS: 0,
      choice_1_MS: 0,
      choice_2_text: "เปรียบเทียบแผนที่กับจุดสังเกตจริงก่อนตัดสินใจ",
      choice_2_next_scene: "ct2_reason",
      choice_2_AS: 2,
      choice_2_MS: 0,
      success_redirect: "ct2_reason",
      fail_redirect: "dah_compass",
      retry_allowed: false,
      allow_save: true,
      ending_type: "",
      score_type: "AS",
      max_score: 2
    },
    dah_compass: {
      scene_id: "dah_compass",
      scene_title: "เสียงกระซิบจากนายพลาธิการ",
      scene_type: "DAH",
      parent_scene: "ctq_compass",
      video_url: "",
      background_image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
      audio_url: "",
      scene_text: "ข้อความสลักเตือนว่า แผนที่อาจหลอกเราเมื่อระดับน้ำขึ้น จงมองหาหลักฐานที่ตรวจสอบได้ในตอนนี้",
      choice_1_text: "ยังคงเชื่อแผนที่เพียงอย่างเดียว",
      choice_1_next_scene: "ct2_reason",
      choice_1_AS: 0,
      choice_1_MS: 0,
      choice_2_text: "ใช้จุดสังเกตที่เห็นจริงและรอยระดับน้ำ",
      choice_2_next_scene: "ct2_reason",
      choice_2_AS: 0,
      choice_2_MS: 2,
      success_redirect: "ct2_reason",
      fail_redirect: "ct2_reason",
      retry_allowed: true,
      allow_save: true,
      ending_type: "",
      score_type: "MS",
      max_score: 2
    },
    ct2_reason: {
      scene_id: "ct2_reason",
      scene_title: "เหตุผลที่เขียนบนผืนทราย",
      scene_type: "CT2",
      parent_scene: "ctq_compass",
      video_url: "",
      background_image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1600&q=80",
      audio_url: "",
      scene_text: "เพราะเหตุใดการตรวจสอบหลักฐานจากหลายแหล่งจึงแข็งแรงกว่าการเชื่อแหล่งเดียว",
      choice_1_text: "ช่วยลดโอกาสที่เบาะแสผิดเพียงชิ้นเดียวจะครอบงำการตัดสินใจ",
      choice_1_next_scene: "ending_gold",
      choice_1_AS: 1,
      choice_1_MS: 0,
      choice_2_text: "เพราะใช้เวลานานกว่า จึงต้องถูกต้องกว่า",
      choice_2_next_scene: "ending_fog",
      choice_2_AS: 0,
      choice_2_MS: 0,
      success_redirect: "ending_gold",
      fail_redirect: "ending_fog",
      retry_allowed: false,
      allow_save: true,
      ending_type: "",
      score_type: "AS",
      max_score: 1
    },
    ending_gold: {
      scene_id: "ending_gold",
      scene_title: "ห้องสมบัติแห่งโคมไฟ",
      scene_type: "END",
      parent_scene: "ct2_reason",
      video_url: "",
      background_image: "https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&w=1600&q=80",
      audio_url: "",
      scene_text: "เส้นทางที่นำด้วยหลักฐานเปิดประตูห้องสมบัติก่อนรุ่งสาง สมบัติเป็นของคุณ และความลับของเกาะก็เช่นกัน",
      choice_1_text: "",
      choice_1_next_scene: "",
      choice_1_AS: 0,
      choice_1_MS: 0,
      choice_2_text: "",
      choice_2_next_scene: "",
      choice_2_AS: 0,
      choice_2_MS: 0,
      success_redirect: "",
      fail_redirect: "",
      retry_allowed: false,
      allow_save: false,
      ending_type: "master_reasoner",
      score_type: "",
      max_score: 2
    },
    ending_fog: {
      scene_id: "ending_fog",
      scene_title: "การกลับมาท่ามกลางหมอก",
      scene_type: "END",
      parent_scene: "ct2_reason",
      video_url: "",
      background_image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
      audio_url: "",
      scene_text: "เกาะมอบทับทิมเม็ดเล็กให้คุณหนึ่งเม็ด พร้อมบทเรียนที่ใหญ่กว่า หลักฐานสำคัญที่สุดในเวลาที่เส้นทางดูเหมือนแน่นอนที่สุด",
      choice_1_text: "",
      choice_1_next_scene: "",
      choice_1_AS: 0,
      choice_1_MS: 0,
      choice_2_text: "",
      choice_2_next_scene: "",
      choice_2_AS: 0,
      choice_2_MS: 0,
      success_redirect: "",
      fail_redirect: "",
      retry_allowed: false,
      allow_save: false,
      ending_type: "partial_discovery",
      score_type: "",
      max_score: 2
    }
  }
};
